document.write("<TABLE WIDTH='565' BORDER='0' CELLSPACING='0' CELLPADDING='0' CLASS='sfont'>")
document.write("    <TR VALIGN='bottom'> ")
document.write("      <TD ALIGN='center' WIDTH='142'><FONT COLOR='#FFFFFF'><A ")
document.write("      HREF='http://www.hd315.gov.cn/beian/view.asp?bianhao=0272000113000001'><IMG HEIGHT=48 ")
document.write("      SRC='http://www.pconline.com.cn/images/biaoshi.gif' WIDTH=40 BORDER=0></A> <BR>")
document.write("        </FONT><A TARGET=_blank HREF='http://www.gdca.gov.cn/'><FONT COLOR='#FFFFFF'>广东省通信管理局</FONT></A>")
document.write("        <BR>")
document.write("        <A TARGET=_blank HREF='http://www.pconline.com.cn/tpy/icp.html'><FONT COLOR='#FFFFFF'>粤ICP证号:000010</FONT></A> ")
document.write("        <BR></TD>")
document.write("      <TD WIDTH='323'>")
document.write("<A HREF=http://www.pconline.com.cn/pconline/index.html><FONT COLOR=ffffff>关于太平洋</FONT></A><FONT COLOR=ffffff> | </FONT><A HREF=http://www.pconline.com.cn/pconline/w6.html><FONT COLOR=#ffffff>网站地图</FONT></A><FONT COLOR=#ffffff> | </FONT><A HREF=http://www.pconline.com.cn/pconline/zinan.html><FONT COLOR=#FFffff>广告指南</FONT></A><FONT COLOR=#ffffff> | </FONT><A HREF=http://www.pconline.com.cn/pconline/contra.html><FONT COLOR=#FFffff>联系我们</FONT></A><FONT COLOR='#FFFFFF'>")
document.write("<BR>网站合作： 1111884(QQ)<BR>")
document.write("        技术报障： </FONT><A HREF='mailto:support@pconline.com.cn'><FONT FACE='Arial, Helvetica, sans-serif' color='#ffffff'>support@pconline.com.cn</FONT><BR>")
document.write("        </A><FONT COLOR='#FFFFFF'>　　　&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 020-87568837")
document.write("        <BR>　　　&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 105205675(QQ)<BR>")
document.write("		对本站有任何建议、意见或投诉，</FONT><A HREF=http://guide.pconline.com.cn/suggest/post.jsp TARGET=_blank><FONT COLOR='#FFFFFF'>请点这里在线提交.</FONT></A>")
document.write("        <BR><FONT COLOR='#FFFFFF'>本网站简体、繁体两种版本，以简体版为准 <BR>")
document.write("        PConline版权所有,未经授权禁止转载、摘编、复制或建立镜像.如有违反,追究法律责任. </FONT> </TD>")
document.write("    </TR>")
document.write("  </TABLE>")
