document.write("<TABLE WIDTH='100%' BORDER='0' CELLSPACING='0' CELLPADDING='2' BGCOLOR='666666'>");
document.write("  <TR VALIGN='middle'> ");
document.write("    <TD HEIGHT='22'>　<A HREF='http://www.pconline.com.cn/pcedu/'><FONT COLOR='#FFFFFF'>学院首页</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/softnews/'><FONT COLOR='#FFFFFF'>软件新闻</FONT></A>  <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/teach/'><FONT COLOR='#FFFFFF'>教你学电脑</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/soft/'><FONT COLOR='#FFFFFF'>软件教室</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/sj/'><FONT COLOR='#FFFFFF'>设计教室</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/empolder/'><FONT COLOR='#FFFFFF'>开发教室</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("      <A HREF='http://www.pconline.com.cn/pcedu/tuijian/'><FONT COLOR='#FFFFFF'>精品导用</FONT></A> <FONT COLOR='#FFFFFF'>|</FONT> ");
document.write("<A href='javascript:window.external.AddFavorite(\"http://www.pconline.com.cn/pcedu/\", \"|&gt;&lt;| 太平洋电脑网->网络学院\")'><FONT COLOR='#FFFFFF'>加入收藏</FONT></A></TD>");
document.write("    </TD>");
document.write("  </TR>");
document.write("</TABLE>");
document.write("<TABLE WIDTH='100%' BORDER='0' CELLSPACING='0' CELLPADDING='2'>");
document.write("<TR><TD HEIGHT='1' BGCOLOR='#000000'></TD></TR>");
document.write("<TR><TD HEIGHT='20' BGCOLOR='#E4E4E4'>&nbsp;&nbsp;<A HREF='http://www9.pconline.com.cn/pcedu/'><FONT COLOR='#000000'>设计素材</FONT></A>");
document.write("      | <A HREF='http://www.pconline.com.cn/pcedu/soft/lan/'><FONT COLOR='#000000'>组网专栏</FONT></A>");
document.write("	  | <A HREF='http://www.pconline.com.cn/pcedu/carton/'><FONT COLOR='#000000'>Flash 剧场</FONT></A> ");
document.write("      | <A HREF='http://www.pconline.com.cn/pcedu/soft/virus/'><FONT COLOR='#000000'>杀毒专区</FONT></A>");
document.write("	  | <A HREF='http://www.pconline.com.cn/pcedu/soft/security/'><FONT COLOR='#000000'>安全在线</FONT></A> ");
document.write("      | <A HREF='http://www.pconline.com.cn/pcedu/qq/'><FONT COLOR='#000000'>QQ大本营</FONT></A>");
document.write("	  | <A HREF='http://www.pconline.com.cn/pcedu/rookie/question/'><FONT COLOR='#000000'>你问我答</FONT></A> ");
document.write("	  | <A HREF='http://www.pconline.com.cn/pcedu/sj/cg/'><FONT COLOR='#000000'>CG专栏</FONT></A> ");
document.write("    </TD></TR>");
document.write("  <TR><TD HEIGHT='1' BGCOLOR='#000000'></TD></TR></TABLE>");