@ctty nul
login b7
call ucdos
if exist m:\bbs\use\a.bas goto a
if exist m:\bbs\use\b.bas goto b
if exist m:\bbs\use\c.bas goto c
if exist m:\bbs\use\d.bas goto d
if exist m:\bbs\use\e.bas goto e
if exist m:\bbs\use\f.bas goto f
if exist m:\bbs\use\g.bas goto g
if exist m:\bbs\use\h.bas goto h
if exist m:\bbs\use\i.bas goto i
if exist m:\bbs\use\j.bas goto j
if exist m:\bbs\use\k.bas goto k 
if exist m:\bbs\use\l.bas goto l 
if exist m:\bbs\use\m.bas goto m 
if exist m:\bbs\use\n.bas goto n 
if exist m:\bbs\use\o.bas goto o 
if exist m:\bbs\use\p.bas goto p 
if exist m:\bbs\use\q.bas goto q 
if exist m:\bbs\use\r.bas goto r 
if exist m:\bbs\use\s.bas goto s 
if exist m:\bbs\use\t.bas goto t 
if exist m:\bbs\use\u.bas goto u 
if exist m:\bbs\use\v.bas goto v 
if exist m:\bbs\use\w.bas goto w 
if exist m:\bbs\use\x.bas goto x 
if exist m:\bbs\use\y.bas goto y 
if exist m:\bbs\use\z.bas goto z 
echo 人数已到达26人,不能再加入!
goto end
:a
move m:\bbs\use\a.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\a.bas
@ctty nul
move m:\bbs\use1\a.bas m:\bbs\use
goto end
:b
move m:\bbs\use\b.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\b.bas
@ctty nul
move m:\bbs\use1\b.bas m:\bbs\use
goto end
:c
move m:\bbs\use\c.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\c.bas
@ctty nul
move m:\bbs\use1\c.bas m:\bbs\use
goto end
:d
move m:\bbs\use\d.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\d.bas
@ctty nul
move m:\bbs\use1\d.bas m:\bbs\use
goto end
:e
move m:\bbs\use\e.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\e.bas
@ctty nul
move m:\bbs\use1\e.bas m:\bbs\use
goto end
:f
move m:\bbs\use\f.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\f.bas
@ctty nul
move m:\bbs\use1\f.bas m:\bbs\use
goto end
:g
move m:\bbs\use\g.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\g.bas
@ctty nul
move m:\bbs\use1\g.bas m:\bbs\use
goto end
:h
move m:\bbs\use\h.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\h.bas
@ctty nul
move m:\bbs\use1\h.bas m:\bbs\use
goto end
:i
move m:\bbs\use\i.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\i.bas
@ctty nul
move m:\bbs\use1\i.bas m:\bbs\use
goto end
:j
move m:\bbs\use\j.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\j.bas
@ctty nul
move m:\bbs\use1\j.bas m:\bbs\use
goto end
:k
move m:\bbs\use\k.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\k.bas
@ctty nul
move m:\bbs\use1\k.bas m:\bbs\use
goto end
:l
move m:\bbs\use\l.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\l.bas
@ctty nul
move m:\bbs\use1\l.bas m:\bbs\use
goto end
:m
move m:\bbs\use\m.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\m.bas
@ctty nul
move m:\bbs\use1\m.bas m:\bbs\use
goto end
:n
move m:\bbs\use\n.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\n.bas
@ctty nul
move m:\bbs\use1\n.bas m:\bbs\use
goto end
:o
move m:\bbs\use\o.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\o.bas
@ctty nul
move m:\bbs\use1\o.bas m:\bbs\use
goto end
:p
move m:\bbs\use\p.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\p.bas
@ctty nul
move m:\bbs\use1\p.bas m:\bbs\use
goto end
:q
move m:\bbs\use\q.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\q.bas
@ctty nul
move m:\bbs\use1\q.bas m:\bbs\use
goto end
:r
move m:\bbs\use\r.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\r.bas
@ctty nul
move m:\bbs\use1\r.bas m:\bbs\use
goto end
:s
move m:\bbs\use\s.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\s.bas
@ctty nul
move m:\bbs\use1\s.bas m:\bbs\use
goto end
:t
move m:\bbs\use\t.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\t.bas
@ctty nul
move m:\bbs\use1\t.bas m:\bbs\use
goto end
:u
move m:\bbs\use\u.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\u.bas
@ctty nul
move m:\bbs\use1\u.bas m:\bbs\use
goto end
:v
move m:\bbs\use\v.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\v.bas
@ctty nul
move m:\bbs\use1\v.bas m:\bbs\use
goto end
:w
move m:\bbs\use\w.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\w.bas
@ctty nul
move m:\bbs\use1\w.bas m:\bbs\use
goto end
:x
move m:\bbs\use\x.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\x.bas
@ctty nul
move m:\bbs\use1\x.bas m:\bbs\use
goto end
:y
move m:\bbs\use\y.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\y.bas
@ctty nul
move m:\bbs\use1\y.bas m:\bbs\use
goto end
:z
move m:\bbs\use\z.bas m:\bbs\use1
@ctty con
@qbasic/run m:\bbs\use1\z.bas
@ctty nul
move m:\bbs\use1\z.bas m:\bbs\use
goto end
:end                             
cls
@ctty con
@login b7




