//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CityBreak.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CITYBREAK_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDC_LONDON                      1000
#define IDC_PARIS                       1001
#define IDC_NEWYORK                     1002
#define IDC_RADIO4                      1003
#define IDC_LUXURY                      1004
#define IDC_STANDARD                    1005
#define IDC_ECONOMY                     1006
#define IDC_DANCE                       1007
#define IDC_CHAMPAGNE                   1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
