//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sdimenu.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SDIMENTYPE                  129
#define IDR_MYCONTEXT                   131
#define ID_MYHEADER_SUBMENU             32771
#define ID_MENUITEM32772                32772
#define ID_MYHEADER_MYSBUONE            32772
#define ID_MENUITEM32773                32773
#define ID_MYHEADER_SUBTWO              32773
#define ID_MENUITEM32774                32774
#define ID_MYHEADER_SUBTHREE            32774
#define ID_CONTEXT_ITEM1                32775
#define ID_CONTEXT_ITEM2                32776
#define ID_CONTEXT_ITEM3                32777
#define ID_CONTEXT_ITEM4                32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
