document.write('<table width="760" border="0" cellspacing="0" cellpadding="1" align="center">');
document.write('  <tr>');
document.write('    <td width="131"><img src="http://btn.pchome.net/logo.gif" width="162" height="68"></td>');
document.write('    <td width="621"><table border="0" cellspacing="1" cellpadding="1" bgcolor="#FFCE65" width="100%">');
document.write('        <tr>');
document.write('          <td bgcolor="#FFFFFF" align="center">');
document.write('');
postadtop();
document.write('');
document.write('          </td>');
document.write('        </tr>');
document.write('      </table></td>');
document.write('  </tr>');
document.write('</table>');
document.write('<table width="760" border="0" cellspacing="0" cellpadding="0" align="center">');
document.write('  <tr>');
document.write('    <td valign="top"><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">');
document.write('        <tr>');
document.write('          <td></td>');
document.write('        </tr>');
document.write('      </table>');
document.write('      <img src="http://btn.pchome.net/head/download.gif" ><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">');
document.write('        <tr>');
document.write('          <td></td>');
document.write('        </tr>');
document.write('      </table></td>');
document.write('    <td width="621" valign="top"><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">');
document.write('        <tr>');
document.write('          <td></td>');
document.write('        </tr>');
document.write('      </table>');
document.write('      <table width="100%" border="0" cellspacing="0" cellpadding="0">');
document.write('        <tr>');
document.write('          <td height="18" colspan="2" bgcolor="#FFDD97">&nbsp;<a href="http://www.pchome.net" class="a1">首页</a>');
document.write('            <span class="indexline">|</span> <a href="http://product.pchome.net" class="a1">产品</a>');
document.write('            <span class="indexline">|</span> <a href="http://market.pchome.net" class="a1">商情</a>');
document.write('            <span class="indexline">|</span> <a href="http://game.pchome.net" class="a1">游戏</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/tips" class="a1">技巧</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/zone" class="a1">专题</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/news/" class="a1">新闻</a>');
document.write('            <span class="indexline">|</span> <a href="http://price.pchome.net" class="a1">报价</a>');
document.write('            <span class="indexline">|</span> <a href="http://club.pchome.net" class="a1">社区</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/review" class="a1">评测</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/search" class="a1">产品查询</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/contact" class="a1">交流合作</a></td>');
document.write('          <td width="4" bgcolor="#CE7F0E">&nbsp;</td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td height="1" colspan="3" bgcolor="#FFFFFF"></td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td height="18" colspan="2" bgcolor="#FFDD97">&nbsp;<a href="http://software.pchome.net" class="a1">软件</a>');
document.write('            <span class="indexline">|</span> <a href="http://download.pchome.net" class="a1">下载</a>');
document.write('            <span class="indexline">|</span> <a href="http://hardware.pchome.net" class="a1">硬件</a>');
document.write('            <span class="indexline">|</span> <a href="http://digi.pchome.net" class="a1">数码</a>');
document.write('            <span class="indexline">|</span> <a href="http://photo.pchome.net" class="a1">摄影</a>');
document.write('            <span class="indexline">|</span> <a href="http://antivirus.pchome.net" class="a1">病毒</a>');
document.write('            <span class="indexline">|</span> <a href="http://ewan.pchome.net" class="a1">译网</a>');
document.write('            <span class="indexline">|</span> <a href="http://shop.pchome.net" class="a1">商城</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/channel" class="a1">渠道</a>');
document.write('            <span class="indexline">|</span> <a href="http://www.pchome.net/" class="a1">企业</a>');
document.write('            <span class="indexline">|</span> <a href="http://club.pchome.net/bbs15.htm" class="a1">二手交流</a>');
document.write('                <span class="indexline">|</span> <a href="http://www.pchome.net/joinus/" target="_blank" class="a1">诚征英才</a> </td>');
document.write('          <td height="18" bgcolor="#CE7F0E">&nbsp;</td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td height="1" colspan="3" bgcolor="#FFFFFF"></td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td width="4" height="18" bgcolor="#FFF2D7">&nbsp;</td>');
document.write('          <td bgcolor="#FFF2D7"><font color="#FA0000"><strong>频道热点</strong></font>| <a href="http://download.pchome.net/newweb/zjbb.htm" target="_blank">装机必备</a>&nbsp;<a href="http://download.pchome.net/newweb/top.htm" target="_blank"><font color=red>TOP10排行榜</font></a>&nbsp;<a href="http://download.pchome.net/tu/" target="_blank">精彩图片</a>&nbsp;<a href="http://download.pchome.net/list.html" target="_blank">分类列表</a>&nbsp;<a href="http://download.pchome.net/xxrk.htm" target="_blank">新新入库</a>&nbsp;<a href="http://download.pchome.net/upinfo.htm" target="_blank">软件发布</a>&nbsp;</td>');
document.write('          <td bgcolor="#CE7F0E">&nbsp;</td>');
document.write('        </tr>');
document.write('      </table>');
document.write('      <table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">');
document.write('        <tr>');
document.write('          <td></td>');
document.write('        </tr>');
document.write('      </table></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height="1" colspan="2" valign="top"></td>');
document.write('  </tr>');
document.write('</table>');