<!-- 
document.write ('<table width="760" border="0" cellspacing="0" cellpadding="0" align="center">');
document.write ('  <tr><td>');
document.write ('      <table width="760" border="0" cellpadding="0" cellspacing="0">');
document.write ('        <tr> ');
document.write ('          <td width="6" height="7" class="bottombg"></td>');
document.write ('          <td width="753" height="7" class="bottombg">');
document.write ('            <table width="100%" border="0" cellspacing="0" cellpadding="4" height="35">');
document.write ('              <tr> ');
document.write ('                <td width="18%" align="center"> <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="127" height="23">');
document.write ('                    <param name="movie" value="http://btn.pchome.net/logo.swf">');
document.write ('                    <param name="quality" value="high">');
document.write ('                    <param name="wmode" value="transparent">');
document.write ('                    <embed src="http://btn.pchome.net/logo.swf" width="127" height="23" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent">');
document.write ('                    </embed> ');
document.write ('                  </object> </td>');
document.write ('                <td align="right" width="82%"> <a href="http://www.pchome.net/aboutus.htm" class="a2" >关于我们</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/contact.htm" class="a2"  >联系方式</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/contact" class="a2"  >广告刊例</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="mailto:market@pchome.net" class="a2"  >业务合作</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/partner.htm" class="a2"  >合作伙伴</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/guide.htm" class="a2"  >投稿指南</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/copyright.htm" class="a2"  >版权声明</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="http://www.pchome.net/help.htm" class="a2"  >帮助信息</a> ');
document.write ('                  <span class="bottomline">|</span> <a href="#" class="a2" >网站地图</a> ');
document.write ('                </td>');
document.write ('              </tr>');
document.write ('            </table>');
document.write ('          </td>');
document.write ('          <td width="6" height="7" class="bottombg"></td>');
document.write ('        </tr>');
document.write ('      </table>');
document.write ('      <table width="760" border="0" cellspacing="0" cellpadding="0">');
document.write ('        <tr><td width="5" height="1" bgcolor="#000000"></td><td width="755" height="1" bgcolor="#000000"></td><td width="5" height="1" bgcolor="#000000"></td></tr>');
document.write ('	 </table>');
document.write ('       </td></tr>');
document.write ('</table>');
document.write ('<table width="760" border="0" cellspacing="0" cellpadding="2" align="center">');
document.write ('  <tr><td class="copyright" align="center"><br>Copyright 1996 - 2003 PChome.net, All Rights Reserved </td></tr>');
document.write ('</table>');
 -->