document.write('<table width="100%" border="0" cellpadding="3" cellspacing="0"><tr><td class=title3>热力推荐</td></tr><tr><td height="1" bgcolor="#CCCCCC"></td></tr><tr><td align="center"><table width="95%" border="0" cellspacing="2" cellpadding="5">');
document.write('                 <tr><td>');
document.write('                   ·[<a href="http://market.pchome.net" target=_blank>商情</a>] <a href="http://article.pchome.net/2003/02/18/1942.htm" target=_blank>工商临检 市场配件变动浑沦</a><br>');
document.write('                   ·[<a href="http://product.pchome.net" target=_blank>产品</a>] <a href="http://article.pchome.net/2003/02/18/1934.htm" target=_blank>七彩虹 镭风9100 CF版初体验</a><br>');
document.write('                   ·[<a href="http://digi.pchome.net" target=_blank>数码</a>] <a href="http://article.pchome.net/2003/02/18/1937.htm" target=_blank>快报!尼康推出颠覆传统的SQ相机!</a><br>');
document.write('                   ·[<a href="http://software.pchome.net" target=_blank>软件</a>] <a href="http://article.pchome.net/2003/03/06/2137.htm" target=_blank>搜索引擎刺刀见红，Google挑战百度</a><br>');
document.write('                   ·[<a href="http://download.pchome.net" target=_blank>下载</a>] <a href="http://www.pchome.net/news/newsc.php?newsid=10044" target=_blank>Netscape可能再无新版</a><br>');
document.write('                   ·[<a href="http://club.pchome.net" target=_blank>社区</a>] <a href="http://digi.pchome.net/2003/1/16/3_26415.htm" target=_blank>如何提高数码相机的利用率？</a><br>');
document.write('                   ·[<a href="http://www.pchome.net/news/" target=_blank>新闻</a>] <a href="http://www.pchome.net/news/2002/12/27/9120.htm" target=_blank>Starcraft：Ghost最新截图</a><br>');
document.write('                   ·[<a href="htt://photo.pchome.net" target=_blank>摄影</a>] <a href="http://photo.pchome.net/all/sal.php?aid=184&said=203" target=_blank>欧罗巴采风--精华--</a>');
document.write('                 </td>');
document.write('                 <td>');
document.write('                   ·[<a href="http://market.pchome.net" target=_blank>商情</a>] <a href="http://article.pchome.net/2003/02/18/1936.htm" target=_blank>罗技耳机大放送! 迎春新举措</a><br>');
document.write('                   ·[<a href="http://product.pchome.net" target=_blank>产品</a>] <a href="http://article.pchome.net/2003/02/14/1883.htm" target=_blank>旌宇 白金版Ti4200-8X全新体验</a><br>');
document.write('                   ·[<a href="http://digi.pchome.net" target=_blank>数码</a>] <a href="http://article.pchome.net/2003/02/10/1814.htm" target=_blank>彩屏天下唯我独尊 松下GD88试用</a><br>');
document.write('                   ·[<a href="http://software.pchome.net" target=_blank>软件</a>] <a href="http://www.pchome.net/from.php?userid=462" target=_blank>最牛强的手指 是你吗?</a><br>');
document.write('                   ·[<a href="http://download.pchome.net" target=_blank>下载</a>] <a href="http://article.pchome.net/2003/02/17/1921.htm" target=_blank>Opera挑衅微软 调侃MSN网站</a><br>');
document.write('                   ·[<a href="http://club.pchome.net" target=_blank>社区</a>] <a href="http://club.pchome.net/2003/1/14/27_4216.htm" target=_blank>孕妇如何选用电脑显示器</a><br>');
document.write('                   ·[<a href="http://game.pchome.net" target=_blank>游戏</a>] <a href="http://game.pchome.net/2003/02/17/39.htm" target=_blank>彩虹3：盾牌行动试玩</a><br>');
document.write('                   ·[<a href="http://game.pchome.net" target=_blank>游戏</a>] <a href="http://game.pchome.net/2003/02/10/38.htm" target=_blank>樱花大战：热き血潮に动画</a>');
document.write('                 </td></tr>');
document.write('              </table> </td></tr></table>');