document.write('<table width="730" bgcolor=white height="50" border="0" align="center" cellpadding="0" cellspacing="0" class="table3">')
document.write('<tr align="center"><td width="92" align=center><a href="http://software.pchome.net/"><strong>软件广场</strong></a></td>')
document.write('<td><table width="100%" border="0" cellpadding="3" cellspacing="0" class="leftline">')
document.write('<tr align="center"><td>')
document.write('<td><a href=http://download.pchome.net/php/hhbd.php>汉化补丁</a></td>')
document.write('<td><a href=http://download.pchome.net/newweb/zjbb.htm>装机必备</td>')
document.write('<td><a href=http://download.pchome.net/newweb/top.htm>下载排行</a></td>')
document.write('<td><a href=http://download.pchome.net/xxrk.htm>新新入库</a></td>')
document.write('<td><a href="http://download.pchome.net/newweb/today.htm">今日更新</a></td></table>')
document.write('</td><td width="92" align=center class="leftline"><strong><a href="http://download.pchome.net/">下载中心</strong></a></td>')
document.write('</tr></table>')