//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SameBall.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SAMEBATYPE                  129
#define IDB_BALL64                      131
#define IDB_BALL48                      132
#define IDB_BALL32                      133
#define IDD_DIALOG1                     133
#define IDD_DIALOG2                     134
#define IDC_EDIT1                       1002
#define IDC_NAME1                       1003
#define IDC_NAME2                       1004
#define IDC_NAME3                       1005
#define IDC_NAME4                       1006
#define IDC_NAME5                       1007
#define IDC_MESSAGE                     1008
#define IDC_SCORE1                      1009
#define IDC_SCORE2                      1010
#define IDC_SCORE3                      1011
#define IDC_SCORE4                      1012
#define IDC_SCORE5                      1013
#define IDW_MUSIC                       4001
#define IDW_KILL                        4002
#define IDW_ACTIVE                      4003
#define IDW_GAMEOVER                    4004
#define ID_VIEW_SCORELIST               32771
#define ID_FILE_LARGE                   32772
#define IDM_REGENDER                    32772
#define ID_FILE_LITTLE                  32773
#define ID_INDICATOR_SCORE              59143
#define ID_INDICATOR_REMAIN             59144
#define ID_INDICATOR_BALLSCORE          59145
#define ID_INDICATOR_COUNT              59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
