#define IDM_OPEN					101
#define IDM_CLOSE					102
#define IDM_READ					103
#define IDM_WRITE					104
#define IDM_GETREADSTATUS		105
#define IDM_GETWRITESTATUS		106
#define IDM_GETDRIVERPARAMS	107
#define IDM_SETDRIVERPARAMS	108
#define IDM_GETDRIVERCAPS		109
#define IDM_ABOUT         110

#define IDC_EDIT1                       1000
#define IDC_STATIC                      -1

#define WM_USER_CALLWRITE 		WM_USER
