#if !defined(AFX_EXWND_H__4607B540_A6C7_11D4_B67F_444553540000__INCLUDED_)
#define AFX_EXWND_H__4607B540_A6C7_11D4_B67F_444553540000__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Exwnd.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// Exwnd window

class Exwnd : public CWnd
{
// Construction
public:
	Exwnd();

// Attributes
public:

// Operations
public:

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(Exwnd)
	//}}AFX_VIRTUAL

// Implementation
public:
	virtual ~Exwnd();

	// Generated message map functions
protected:
	//{{AFX_MSG(Exwnd)
		// NOTE - the ClassWizard will add and remove member functions here.
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXWND_H__4607B540_A6C7_11D4_B67F_444553540000__INCLUDED_)
