// Exwnd.cpp : implementation file
//

#include "stdafx.h"
#include "ExDDraw.h"
#include "Exwnd.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// Exwnd

Exwnd::Exwnd()
{
}

Exwnd::~Exwnd()
{
}


BEGIN_MESSAGE_MAP(Exwnd, CWnd)
	//{{AFX_MSG_MAP(Exwnd)
		// NOTE - the ClassWizard will add and remove mapping macros here.
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()


/////////////////////////////////////////////////////////////////////////////
// Exwnd message handlers
