//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MLaunch.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MLAUNCH_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_MODELESS                    129
#define IDC_POP                         1003
#define IDC_POW                         1004
#define IDC_EDIT1                       1005
#define IDC_START_MODELESS              1006
#define IDC_SOP_MODELESS                1007
#define IDC_LIST1                       1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
