//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Rotary.rc
//
#define IDS_ROTARY                      1
#define IDD_ABOUTBOX_ROTARY             1
#define IDB_ROTARY                      1
#define IDI_ABOUTDLL                    1
#define IDS_ROTARY_PPG                  2
#define IDS_ROTARY_PPG_CAPTION          200
#define IDD_PROPPAGE_ROTARY             200
#define IDC_TICKS_ENABLED               204
#define IDC_NUM_TICKS                   205
#define IDC_SPIN1                       207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         209
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
