//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mciwnd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MCIWND_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_PLAY                        1000
#define IDC_OPENVIDEO                   1000
#define IDC_OPEN                        1001
#define IDC_CLOSE                       1002
#define IDC_PLAYVIDEO                   1002
#define IDC_PAUSE                       1003
#define IDC_LAST                        1005
#define IDC_NEXT                        1006
#define IDC_CLOSEVIDEO                  1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
