//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MDICoin.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MDICOITYPE                  129
#define IDR_MDIBILLTYPE                 130
#define IDR_MDIBILTYPE                  130
#define ID_EDIT_ADD_COIN                32771
#define ID_EDIT_REMOVE_COIN             32772
#define ID_EDIT_ADD_BILL                32773
#define ID_EDIT_REMOVE_BILL             32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
