document.writeln('<table border="0" cellspacing="0" cellpadding="0" align="center" height=70><tr><td style="line-height:19px">');
document.writeln("<a href=\"#\" onclick=\"window.open('http://sms.tom.com/index2.php?inc=smc_menu');return false;\"><font color=\"#FF0000\">订阅：包月9元精彩无限！</a><br>");
document.writeln("<a href=\"#\" onclick=\"window.open('http://sms.tom.com/open_example.php?pid=4175&refer=TOM','','width=370,height=250');return false;\">订阅： 爱 情 心 理</a><br>");
document.writeln("<a href=\"#\" onclick=\"window.open('http://sms.tom.com/open_example.php?pid=4176&refer=TOM','','width=370,height=250');return false;\">订阅： 求 爱 宝 典</a><br>");
document.writeln("<a href=\"#\" onClick=\"window.open('http://sms.tom.com/open_example.php?pid=4178&refer=TOM','','width=370,height=250');return false;\">订阅： 追求漂亮 MM</a><br>");
document.writeln("<a href=\"#\" onclick=\"window.open('http://sms.tom.com/tupian_step0.php?var=0yyGBwqd%7Cv051gaKRJ%2BUscqg%2BoHIuOQfRmkIa43QmxHR8YubAVzwAlGSX0VWxmEBeruwukPkWNY6LNBopVRkcgL1ZNMcd9Aj4vdxolbVhh6essYaRIEl%2Bh8eRLN0mgXBCM1dKW9kO%2F6V3cFsQGgIc2GZi5enHdszmOsCR8hNMeQTLJSht3R8.&refer='+escape(window.location.href)+'','','width=432, height=240');\"><img src=\"http://smsad.tom.com/smsweb/images/modpic/3740_1321/Tom_1028619391.bmp\" border=\"0\"></a>&nbsp;<a href=\"#\" onclick=\"window.open('http://sms.tom.com/tupian_step0.php?var=0yyGBwqd%7CRVGX1kotnyH1gJzMogA48OGnLgoepp6OIUelvJ1YDh4sqhgM%2FXfZMd6LWafE7qrz%2B7FaJIUTKcGPVJBGOVEpjs5RGs6yNy0fk9daa9oV67QVuiZsTmX4j%2BwJXYFMdm9W6FYvCb%2FjvZDKwVatNEHwFLJEdnlwczwPg0dZl5vmHZ8.&refer='+escape(window.location.href)+'','','width=432, height=240');\"><img src=\"http://smsad.tom.com/smsweb/images/modpic/3740_1321/Tom_1028619518.bmp\" border=\"0\"></a><br>");	
document.writeln("<a href=\"#\" onclick=\"window.open('http://sms.tom.com/tupian_step0.php?var=0yyGBwqd%7CO80v2YYdAbCUfJsRl%2FHe%2FoM%2BrEds0d7Sf6H3DmafgZlRDrwhbKD62UptNZoNBPG8Wfwp%2FZ4lmtY%2BzbQS9Gur1JDgNJVI7ikAESURnJ29XpYnjPew3HRPue0h9WFWo7YeX6Q4ujFCkwyixiYIJdwIqpljCGcoh7U4aIhcRlXD4RM.&refer='+escape(window.location.href)+'','','width=432, height=240');\"><img src=\"http://smsad.tom.com/smsweb/images/modpic/29_1156/Tom_1028789765.bmp\" border=\"0\"></a>&nbsp;<a href=\"#\" onclick=\"window.open('http://sms.tom.com/tupian_step0.php?var=0yyGBwqd%7CmNRtSqDAVAk4nw9PvpSzFnZDzqpXKG1yj%2BXWbVK3iBJfBxqaafsvlALF8ejHnavCBiZdgbREYiWNLNYSI9AfWaHkAnZVcgqZ16m1JmRNpGIFNcK1wj0ux4tONx52jbdbVaTfV4cw6IlFIUVGB7Ql0pUdciL0KE2ZeAMtktC%2FK5g.&refer='+escape(window.location.href)+'','','width=432, height=240');\"><img src=\"http://smsad.tom.com/smsweb/images/modpic/29_1320/Tom_1028619209.bmp\" border=\"0\"></a><br>");
document.writeln("<a href=\"http://sms.tom.com/index2.php?inc=3&order_by=Sum\" target=\"_blank\" style=\"text-decoration:underline;font-size: 12px\">铃声</a>：<a href=\"#\" onclick=\"window.open('http://sms.tom.com/lingsheng_step0.php?var=0yyGBwqd%7CgH4RTDvvMNbzrviwy9DDnIoAYrBeEfC1ODJQ1lBCYDSBZu4sdfzuAVECLb68GT1M%2BjeXnlOYBiEVTS%2BnrcPVzlvwmd0dffleoz2brlJccTnaSxcdYiJRDONfQnSedtAbLIu%2BshpSVF4Sa%2Fc1PoSdCvvdf3SQFNF1FmDpVE%2Fo8cs.%7CMWORAh9wd2Uh4YJT2ipc7hgdqMwreK9ch1WSWNDbCStDTHL2oZTqx4Rhnfw8CwUNjoNjL0xX2bjcdxuSh5M8xyx3YGKwwb1RVhtNKhkepcd58W5RuLULsS0GKU%2BE81W9n5NM6FMOmEprkMazDZR5i2bQBd4%2Bqtox00od8c1DrSM.&refer='+escape(window.location.href)+'','','width=432, height=240' );\" style=\"text-decoration:underline;font-size: 12px\">沧海一声笑(任贤齐)</a><br>");
document.writeln("<a href=\"http://sms.tom.com/index2.php?inc=3&catalog_id=613&type=3995&order_by=Sum&temp=1\" target=\"_blank\" style=\"text-decoration:underline;font-size: 12px\">铃声</a>：<a href=\"#\" onclick=\"window.open('http://sms.tom.com/lingsheng_step0.php?var=0yyGBwqd%7CxiU7rAIFXGgZki1JwhA1kZ%2BBDgUyv7BOzchtRPiHlAvrTNEalDFHZqAioxxK07vwguzYrCM6KMSHP5FMXl4agKS62lIz1W50xDIGjPd5iYGYT36VICfzDp5gwUw582S7BoOON9WqpFjn524HVXSJMWOjST9GL%2Bw8O%2BMe8MDLpEs.%7CDQckRZgjzz0UNKuURrlZHyS3X5VtgbHMBE609MPe1nUyc5KQ6gLJNKdlP3zw3TkxAIVDHo9qAqg%2FEiuazRK1fmcNNnaV5z91Tdv58iG37hypdHXVVTt3MkvBfMA8aS3QxSZE4R%2BjT%2F%2F%2B08snlgBTmwzMwMQD9szmK847RdXmBkI.&refer='+escape(window.location.href)+'','','width=432, height=240' );\" style=\"text-decoration:underline;font-size: 12px\">很爱很爱你(刘若英)</a><br>");
document.writeln("<a href=\"http://sms.tom.com/index2.php?inc=3&catalog_id=&type=26&order_by=Sum&temp=1\" target=\"_blank\" style=\"text-decoration:underline;font-size: 12px\">铃声</a>：<a href=\"#\" onclick=\"window.open('http://sms.tom.com/lingsheng_step0.php?var=0yyGBwqd%7CZI1LBfbT2A3HjH9jbqb9%2F1rmsdvbA%2F7tZP7cdXs%2FOf8ngcdO%2B1vo4dNbpGZ5M%2FteVT%2B6bPZiWXaOaCYoLAEDikGpA91MG0M3lNKEckwV%2BxINEklzhi3e6sq2oFFkgcQkz9fyuwGJAkR3uyHpR2xzoNEdrQ6pF%2Bc3hz2qIH4qVrY.%7CydfxwgTziBum5Lm0rEx3v6vJ5Frb4CNVOb4OcnKMUKtDr0jpFRBGGSht238ZgluuY5c0l82jTFhjN5boY5lrStDDWLL3JT2pUnMNtoR8wEp5jKL0we3P%2BSLCIReJ3YiCszwU7ph%2BZV0heGBrb3cHgMZ0tbXDOh13V6qzIUphegk.&refer='+escape(window.location.href)+'','','width=432, height=240' );\" style=\"text-decoration:underline;font-size: 12px\">眉飞色舞(郑秀文)</a><br>");
document.writeln("<a href=\"http://sms.tom.com/index2.php?inc=3&catalog_id=67&type=25&order_by=Sum&temp=1\" target=\"_blank\" style=\"text-decoration:underline;font-size: 12px\">铃声</a>：<a href=\"#\" onclick=\"window.open('http://sms.tom.com/lingsheng_step0.php?var=0yyGBwqd%7Ct1T8%2Bj0YBPla%2FI%2BiyW4sq629Q%2BuklS%2FPeRQREAX4kKh8FIysNJR4uIj2YIib6ZT7WESkvWpKUXJ9scDa%2BykXkUlhtaCGtccrVJJtYUhRUqxjeNbozW%2B%2B%2BrJYqjvaPYwWr0TSMvgOSIHmTTWWJYTL5xrM3yplyrTa%2BdWd4PLxhOc.%7CbSJvi%2B1ITIJkKuQuWXMAjFmy%2FHcUMDIv16pfoOkrv4Dz4x7cWtLJtyncCcnvLaGWjKJWaXacFbFnnMScxPQbQTnv5Ik%2B%2BspQE68ZJSPoVr2UwiZLKK7RwYCyy1JOFBEHweudaL%2BJgSwSvb8ZXDfelS7JM2%2FC6esE4TeaxnFEHjc.&refer='+escape(window.location.href)+'','','width=432, height=240' );\" style=\"text-decoration:underline;font-size: 12px\">城里的月光(许美静)</a>");
document.writeln('</td></tr></table>');
document.writeln('<table border=\"0\" cellspacing=\"1\" cellpadding=\"0\" align=center>');
function clearfield(){
if(document.sms.query_name.value == "输入歌曲 / 歌手找铃声")
document.sms.query_name.value = "";
}
document.writeln('<form name=sms action=\"http://sms.tom.com/index2.php?inc=3\" method=\"post\" target=\"_blank\">');
document.writeln('<tr><td colspan=2><input type=\"text\" name=\"query_name\" size=20 value=\"输入歌曲 / 歌手找铃声\" onclick=\"clearfield();\" style=\"font-size:12px\"></td></tr>');
document.writeln('<tr><td>');
document.writeln('<select name="search_type" class=input>');
document.writeln('<option value=\"24\">诺基亚</option>');
document.writeln('<option value=\"25\">西门子</option>');
document.writeln('<option value=\"26\">摩托罗拉&nbsp;&nbsp;</option>');
document.writeln('</select></td>');
document.writeln('<td width=16 style=\"padding:0px 0px 1px 0px\"><input type=\"submit\" value=\"查找\" style=\"font-size: 12px\"></td>');
document.writeln('</tr>');
document.writeln('<input type=\"hidden\" name=\"flag\" value=1></form>');
document.writeln('</table>');