// Machine generated IDispatch wrapper class(es) created with ClassWizard
/////////////////////////////////////////////////////////////////////////////
// IAutoserver wrapper class

class IAutoserver : public COleDispatchDriver
{
public:
	IAutoserver() {}		// Calls COleDispatchDriver default constructor
	IAutoserver(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	IAutoserver(const IAutoserver& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double SquareRoot(double dInputVal);
};
