//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by exCD.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXCD_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_SET                         129
#define IDC_TRACK                       1000
#define IDC_PLAY                        1001
#define IDC_PLAYMODE                    1002
#define IDC_FMINI                       1002
#define IDC_FSECOND                     1003
#define IDC_PAUSE                       1004
#define IDC_LAST                        1005
#define IDC_TMINI                       1005
#define IDC_NEXT                        1006
#define IDC_TSECOND                     1006
#define IDC_EJECT                       1007
#define IDC_STOP                        1008
#define IDC_BUTTON1                     1008
#define IDC_BUTTON2                     1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
