//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Example5E.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXAMPLE5E_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_AVI1                        130
#define IDC_ANIMFRAME                   1000
#define IDC_EDIT1                       1001
#define IDC_BROWSE                      1002
#define IDC_CENTER                      1003
#define IDC_TRANSPARENT                 1004
#define IDC_AUTOPLAY                    1005
#define IDC_STYLE                       1006
#define IDC_PLAY                        1007
#define IDC_STOP                        1008
#define IDC_ANIMATE                     1009
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
