//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Example5D.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EXAMPLTYPE                  129
#define IDI_ICON1                       143
#define IDI_ICON2                       144
#define IDI_ICON3                       145
#define IDI_ICON4                       146
#define IDI_ICON5                       147
#define IDI_ICON6                       148
#define IDI_ICON7                       149
#define IDI_ICON8                       150
#define IDI_ICON9                       151
#define IDI_ICON10                      152
#define IDI_STATUSICON1                 153
#define IDI_STATUSICON2                 154
#define IDI_STATUSICON3                 155
#define IDI_STATUSICON4                 156
#define IDI_STATUSICON5                 157
#define IDI_STATUSICON6                 158
#define IDI_STATUSICON7                 159
#define IDI_STATUSICON8                 160

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
