//È¡×ÔJava³ÌÐò

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class TestDll */

#ifndef _Included_TestDll
#define _Included_TestDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestDll
 * Method:    NewData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jni_TestDll_NewData
  (JNIEnv *, jclass);

/*
 * Class:     TestDll
 * Method:    jstring
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_TestDll_jstring
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
