//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VideoPlayer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VIDEOPLAYER_DIALOG          102
#define IDD_PLAYER_DLG                  102
#define IDR_MAINFRAME                   128
#define IDD_DISPLAY                     130
#define IDD_SPEED                       131
#define IDI_ICON1                       133
#define IDC_OPEN                        1000
#define IDC_STOP                        1001
#define IDC_PAUSE                       1002
#define IDC_PLAY                        1003
#define IDC_NEXT                        1004
#define IDC_PREV                        1005
#define IDC_LAST                        1005
#define IDC_VIDEO_NAME                  1006
#define IDC_INFORMATION                 1007
#define IDC_CLOSE                       1008
#define IDC_FRAMES                      1009
#define IDC_DEMENSION                   1010
#define IDC_PLAY_SPEED                  1011
#define IDC_PLAY_SOUND                  1012
#define IDC_DISPLAY                     1013
#define IDC_POPDIS                      1016
#define IDC_POPDIS1                     1018
#define IDC_SCROLLBAR                   1020
#define IDC_DISPLAYBOX                  1022
#define IDC_EDITNAME                    1023
#define IDC_EDITFRAMES                  1024
#define IDC_EDITRECT                    1025
#define IDC_EDITSPEED                   1026
#define IDC_LOOP                        32771
#define IDC_FULLSCREEN                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
