//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hotspot4.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define IDC_LINKTEXT                    1000
#define IDDELETE                        1001
#define IDC_LINKLIST                    1002
#define ID_FILE_SAVEHOTSPOT             32771
#define ID_EDIT_EDITHOTSPOT             32772
#define ID_MODE_DEFINE                  32773
#define ID_MODE_TEST                    32774
#define IF_FILE_NEWHOTSPOT              32775
#define ID_FILE_NEWHOTSPOT              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
