//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by waver.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WAVER_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_DISPLAY                     129
#define IDC_PLAY                        1000
#define IDC_OPEN                        1001
#define IDC_RECORD                      1002
#define IDC_STOP                        1003
#define IDC_SAVE                        1004
#define IDC_INFO                        1005
#define IDC_STATUS                      1006
#define IDC_PROCING                     1007
#define IDC_ENAME                       1013
#define IDC_ECHANNEL                    1014
#define IDC_ESAM                        1016
#define IDC_ELONG                       1018
#define IDC_EBIT                        1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
